function [tau_vec, nu_vec, tau_phys, nu_phys, theta_s, phi_s, theta_r, phi_r] = generate_phys_dd_paths(cfg, Lch, rng_seed)
%GENERATE_PHYS_DD_PATHS  Generate delay-Doppler indices from physical parameters
%
%   Generates physically meaningful delay and Doppler indices for AFDM/AFWDM
%   channel simulation. The first path is always the reference path (tau=0).
%   Doppler shifts are generated using Jakes-like angular projection.
%
%   INPUTS:
%     cfg      - Configuration struct containing:
%                .tau_max  - Maximum physical delay [s]
%                .nu_max   - Maximum physical Doppler [Hz]
%                .Ts       - Sampling period (delay resolution) [s]
%                .Deltaf   - Subcarrier spacing [Hz]
%                .lmax     - Maximum delay index
%                .kmax     - Maximum Doppler index
%     Lch      - Number of channel taps (paths)
%     rng_seed - Random seed for reproducibility
%
%   OUTPUTS (legacy, positions 1-4 unchanged for backward compat):
%     tau_vec  - Discrete delay indices [0, lmax], integer, length Lch
%     nu_vec   - Discrete Doppler indices [-kmax, kmax], integer, length Lch
%     tau_phys - Physical delays [s] (before discretization)
%     nu_phys  - Physical Dopplers [Hz] (before discretization)
%
%   OUTPUTS (cc-0518-03 NEW, per-path angles for paper Eq. (26)):
%     theta_s  - Tx-side elevation per path, in [0, pi/2], length Lch
%     phi_s    - Tx-side azimuth   per path, in [0, 2*pi],  length Lch
%     theta_r  - Rx-side elevation per path, in [0, pi/2], length Lch
%     phi_r    - Rx-side azimuth   per path, in [0, 2*pi],  length Lch
%     Used by beamspace_apd_channel_2d_perpath.m to build per-path tilt
%     vectors so each path has its own dominant direction.
%
%   Reference:
%     GSM-AFDM paper: l1=0, lp in U[1,lmax], kp via Jakes spectrum
%     AFWDM paper Eq. (26): per-path (theta_p, phi_p) on both Tx/Rx sides
%
%   Author: Generated by Claude Code
%   Date: 2026-03-24 (extended 2026-05-18 cc-0518-03)

    rng(rng_seed);

    % ---- Delays: first path is reference (tau = 0) ----
    tau_phys = zeros(1, Lch);
    if Lch > 1
        % Generate random delays for remaining paths, sorted in ascending order
        tau_phys(2:end) = sort(rand(1, Lch-1) * cfg.tau_max);
    end

    % ---- Doppler: Jakes-like angular projection ----
    % nu = nu_max * cos(phi), where phi is uniformly distributed
    phi = -pi + 2*pi*rand(1, Lch);  % phi ~ U[-pi, pi]
    nu_phys = cfg.nu_max * cos(phi);   % [Hz], range [-nu_max, nu_max]

    % ---- Map physical quantities to discrete indices ----
    tau_vec = round(tau_phys / cfg.Ts);
    nu_vec  = resolve_doppler(nu_phys / cfg.Deltaf, cfg);

    % ---- Force constraints ----
    tau_vec(1) = 0;  % Reference path must have zero delay

    % Clamp to valid range
    tau_vec = min(max(tau_vec, 0), cfg.lmax);
    nu_vec  = min(max(nu_vec, -cfg.kmax), cfg.kmax);

    % ---- Per-path angles (cc-0518-03, paper Eq. (26)) ----
    % Each path p has independent dominant direction on Tx and Rx side.
    % Elevation theta in [0, pi/2] (upper hemisphere), azimuth phi in
    % [0, 2*pi]. Sampling is uniform on the sphere via inverse-cosine for
    % elevation so the resulting wavevector kx = sin(theta)*cos(phi),
    % ky = sin(theta)*sin(phi) is uniform on the propagation disk.
    theta_s = acos(rand(1, Lch));   % U on cos(theta), giving uniform-on-disk
    phi_s   = 2*pi * rand(1, Lch);
    theta_r = acos(rand(1, Lch));
    phi_r   = 2*pi * rand(1, Lch);

    % ---- Sanity checks ----
    assert(tau_vec(1) == 0, 'First path delay must be 0 (reference path)');
    assert(all(tau_vec >= 0), 'All delay indices must be non-negative');
    assert(all(tau_vec <= cfg.lmax), 'Delay indices exceed lmax');
    assert(all(abs(nu_vec) <= cfg.kmax), 'Doppler indices exceed kmax');
    assert(all(theta_s >= 0 & theta_s <= pi/2), 'theta_s out of [0,pi/2]');
    assert(all(theta_r >= 0 & theta_r <= pi/2), 'theta_r out of [0,pi/2]');

end