function [plan, mode_states, outcome] = ...
        build_time_diversity_exploration_completion( ...
        stage_plan, final_results, cfg_final)
%BUILD_TIME_DIVERSITY_EXPLORATION_COMPLETION Label an explicit candidate run.

if isempty(stage_plan)
    error('build_time_diversity_exploration_completion:missingPlan', ...
        'Explicit exploration completion requires at least one stage.');
end
last = stage_plan(end);
mode_states = initialize_time_diversity_mode_states( ...
    cfg_final.time_diversity.doppler_modes);
gabp_row = strcmp(final_results.summary_table.detector, 'gabp');
gain_db = NaN;
claim_eligible = false;
if any(gabp_row)
    row = find(gabp_row, 1);
    gain_db = final_results.summary_table.snr_gain_db(row);
    claim_eligible = isfinite(gain_db) && ...
        ~final_results.summary_table.noise_limited(row);
end
mode_states(1).status = 'candidate';
mode_states(1).evidence_stage = last.name;
mode_states(1).gain_db = gain_db;
mode_states(1).claim_eligible = claim_eligible;

audits = [stage_plan.audit];
plan = struct( ...
    'current_stage', last.name, ...
    'next_stage', 'exploration_complete', ...
    'stage_order', {{stage_plan.name}}, ...
    'single_variable_changes', {{stage_plan.single_variable_change}}, ...
    'kmax', audits(end).kmax, ...
    'lmax', audits(end).lmax, ...
    'diversity_lhs', audits(end).diversity_lhs, ...
    'diversity_condition_passed', audits(end).diversity_condition_passed, ...
    'fail_closed', false);
outcome = struct( ...
    'status', 'candidate', ...
    'state_machine_status', 'exploration_complete', ...
    'final_stage', last.name, ...
    'per_doppler', mode_states, ...
    'parameters', struct( ...
        'v_max_kmh', cfg_final.v_max_kmh, ...
        'kmax', audits(end).kmax, ...
        'tau_max_us', cfg_final.tau_max_us, ...
        'lmax', audits(end).lmax, ...
        'Lch_values', cfg_final.time_diversity.Lch_values, ...
        'doppler_modes', {cfg_final.time_diversity.doppler_modes}, ...
        'detectors', {cfg_final.time_diversity.detectors}, ...
        'spatial_pairs', {cfg_final.time_diversity.spatial_pairs}), ...
    'production_result_available', false);
end
